## See https://pub.dev/packages/build_config
#targets:
#  $default:
#    builders:
#      json_serializable:
#        options:
#          any_map: true
#          checked: true
#          create_to_json: false
#          disallow_unrecognized_keys: true
#          field_rename: snake
#


targets:
  $default:
    sources:
      - swaggers/**
      - lib/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          #output_folder: "lib/src/repositories/gen"
          output_folder: "lib/gen"
          #separate_models: true
          build_only_models: true
          #ignore_headers: true
          use_inheritance: false
          default_values_map:
            #- type_name: int
            #  default_value: '36'
            #- type_name: String
            #  default_value: 'default'
            #- type_name: 'List<String>'
            #  default_value: '[]'
#          exclude_paths:
#            - '/api/user/profile/get_custom_fields'
#          response_override_value_map:
#            - url: '/api/user/profile/get_custom_fields'
#              method: get
#              overridden_value: "BlaBlaBla"