name: insidersapp
description: Insiders

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  phosphor_flutter: ^1.3.1

  #adaptive_dialog: ^1.2.0
  flutter_platform_widgets: ^1.12.0

  flutter_dotenv: ^5.0.2

  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  rxdart: ^0.27.3

  # logging
  catcher: ^0.6.9
  sentry: ^6.2.2

  formz: ^0.4.1
  equatable: ^2.0.3
  uuid: ^3.0.5

  # storage
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.11
  hive_flutter: 1.1.0

  # objects
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  # network
  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1
  #dio_cache_interceptor: ^3.0.3
  #dio_cache_interceptor_hive_store: ^3.0.1
  stash: ^3.2.2
  stash_dio: ^3.2.2
  #fresh_dio: ^0.3.1
  dio_smart_retry: ^1.1.0

  #http: ^0.13.4
  #chopper: ^4.0.3
  #chopper_built_value: ^1.0.0

  jwt_decode: ^0.3.1

  #animations: ^2.0.2

  connectivity_plus: ^2.1.0
  package_info_plus: ^1.3.0
  #network_info_plus: ^2.1.0
  #device_info_plus: ^3.1.1

  share_plus: ^3.0.4

  # widgets
  flutter_svg: ^1.0.0
  modal_bottom_sheet: ^2.0.0
  pinput: ^1.2.2
  #like_button: ^2.0.3
  timeago: ^3.1.0
  #showcaseview: ^1.1.3
  intl_phone_number_input: ^0.7.0+2
  infinite_scroll_pagination: ^3.1.0

  # flutter flow
  #auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  #intl_utils: ^2.5.1
  page_transition: ^2.0.4
  url_launcher: ^6.0.17

  # navigation
  # flow_builder: ^0.0.6
  auto_route: ^3.2.0

  dartz: ^0.10.1
  recase: ^4.0.0
  enum_to_string: ^2.0.1
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  swagger_dart_code_generator: ^2.2.10
  #chopper_generator: ^4.0.3

  flutter_lints: ^1.0.4

  bloc_test: ^9.0.1
  mocktail: ^0.2.0
  #mockito: ^5.0.16

  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.3

  hive_generator: 1.1.1
  json_serializable: ^6.1.1
  freezed: ^1.1.0

  path_provider: ^2.0.8

  auto_route_generator: ^3.2.0

  flutter_native_splash: ^1.3.2

  rename: ^2.0.1

  import_sorter: ^4.6.0

  very_good_analysis: ^2.4.0


flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/env/

import_sorter:
  comments: false
  emojis: false