name: insidersapp
description: Insiders

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  phosphor_flutter: ^1.3.1

  flutter_platform_widgets: ^1.11.1

  flutter_dotenv: ^5.0.2

  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0

  formz: ^0.4.1
  equatable: ^2.0.3
  uuid: ^3.0.5

  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.9
  hive_flutter: 1.1.0

  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0

  dio: ^4.0.4
  pretty_dio_logger: ^1.1.1

  jwt_decode: ^0.3.1

  animations: ^2.0.2

  connectivity_plus: ^2.0.3
  package_info_plus: ^1.3.0
  #network_info_plus: ^2.1.0
  #device_info_plus: ^3.1.1

  # widgets
  flutter_svg: ^0.23.0+1
  modal_bottom_sheet: ^2.0.0
  pinput: ^1.2.2
  like_button: ^2.0.3
  timeago: ^3.1.0
  #showcaseview: ^1.1.3
  intl_phone_number_input: ^0.7.0+2

  # flutter flow
  #auto_size_text: ^3.0.0
  cached_network_image: ^3.1.0+1
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  #intl: ^0.17.0
  page_transition: ^2.0.4
  url_launcher: ^6.0.15

  # navigation
  auto_route: ^3.1.3
  # flow_builder: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  bloc_test: ^9.0.1
  #mocktail: ^0.2.0
  #mockito: ^5.0.16

  build_runner: ^2.1.5
  flutter_gen_runner: ^4.1.2

  hive_generator: 1.1.1
  json_serializable: ^6.0.1
  freezed: ^1.0.0

  path_provider: ^2.0.7

  auto_route_generator: ^3.1.0


flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/env/
